// ignore_for_file: constant_identifier_names

import 'package:artifact_library/character/character.dart';

enum Characters {
  Kirara(
    Character(
      '綺良々',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/05/23/132746206/05015541c4d22079c8415938c9cbbe51_9137165015004286789.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/05/23/132746206/d1699810632f8c3bc8c1e8c8beb8250f_7472608897166444404.png',
      4,
      '稲妻の配達会社「狛荷屋」の配達員。仕事を愛し、人間社会に憧れている「猫又」。',
      Elements.Dendro,
    ),
  ),
  Baizhu(
    Character(
      '白朮',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/04/28/132746206/0a29bc885777e12ff3db57de89034281_3530849294645107482.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/04/28/132746206/05599650d7f42e1c4adde373de6b297d_4443391405678036890.png',
      5,
      '薬舗「不卜廬」の店主。「長生」という名の白蛇を体に乗せている。薬に精通しており、いつも深く考えを巡らせているが、他人が彼の思考を読み取ることは難しい。',
      Elements.Dendro,
    ),
  ),
  Kaveh(
    Character(
      'カーヴェ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/04/30/132746206/8706d0f6385f31a35b94a761d4a7a627_1135049512919014002.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/04/30/132746206/2270aba02b92034d7d76b4426be8f53b_2538508507377778329.png',
      4,
      'スメールの著名建築デザイナー。多くの物事に対し、行き過ぎた思いやりの心を持つ。唯美主義者だが、現実に悩まされている。',
      Elements.Dendro,
    ),
  ),
  Dehya(
    Character(
      'ディシア',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/02/26/132746206/dbba9ee7329ca34cc3a5e0449cc4c4c0_8499016132699571342.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/02/24/132746206/65b22311e1e38ffa45a4928d4005ecee_2188861075808735208.png',
      5,
      'スメールの砂漠を気の赴くままに渡り歩く傭兵集団「エルマイト旅団」のメンバー。屈強で勇敢な戦士。「エルマイト旅団」ではかなり名が通っている。',
      Elements.Pyro,
    ),
  ),
  Mika(
    Character(
      'ミカ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/03/19/132746206/c23402e9898c07b79495d181deca4c13_800403129704433139.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/03/19/132746206/da13e3b1a2c6c0e5892b201cec735f9b_6427639047927610211.png',
      4,
      '平凡な家庭に生まれた若い騎士。小隊では「前進測量士」を担当している。控えめで慎重な性格の持ち主。',
      Elements.Cryo,
    ),
  ),
  Alhaitham(
    Character(
      'アルハイゼン',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/01/15/86506456/263c92ac7b067f2bbe5498291ff1827c_7005663213021458311.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/01/15/86506456/25249dd20b86c775fb35bdbbd805d9ec_1537379380548664325.png',
      5,
      'スメール教令院の現書記官。並外れた知恵と才能の持ち主。悠々自適の生活を送っており、人に行方を知られることは滅多にない。',
      Elements.Dendro,
    ),
  ),
  Yaoyao(
    Character(
      'ヨォーヨ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/01/18/103265111/c178874ca89b6da072c6e7e7908d12f2_4282648778481726239.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2023/01/18/103265111/5bc9df1fb67391e4c8080da3d855de53_5443256069049270925.png',
      4,
      '歌塵浪市真君のもっとも幼い弟子。優しくて思いやりのある「おませさん」。',
      Elements.Dendro,
    ),
  ),
  Wanderer(
    Character(
      '放浪者',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/12/06/194600931/12542bc6cf68564e0327323e42658815_5313786699068740489.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/12/06/194600931/24d97a22be742fb732ea96f625d1faac_6118070969113943866.png',
      5,
      '正体が謎に包まれた放浪者。のような身なりをしているが、それらしき言動は見られない。',
      Elements.Anemo,
    ),
  ),
  Faruzan(
    Character(
      'ファルザン',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/12/06/194600931/68f891b9f68ab114977e00200efb9e59_1458317065452179306.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/12/06/194600931/38c12ab46678a4008f83a0e46c900ef5_7031784280892508005.png',
      4,
      '「百年前」から訪れた学者。自ら好んで先輩と名乗り、各種古代文字や古典ギミックに精通している。',
      Elements.Anemo,
    ),
  ),
  Layla(
    Character(
      'レイラ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/11/17/103265111/d78c64527941436b02a89131c5da9607_5733856321723765856.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/11/17/103265111/48a495acadaf37f12d0a7f653d85bd83_251694765760736227.png',
      4,
      '理論占星学を専攻するルタワヒスト学院の学生。時々夢遊状態になる。寝不足が長期にわたり続いており、睡眠障害に悩まされている。',
      Elements.Cryo,
    ),
  ),
  Nahida(
    Character(
      'ナヒーダ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/10/31/103265111/6e1e5196da96bd65e549abe7fa861915_6441979623331954875.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/10/31/103265111/f29490bddc56b4a6773b6c5003bbb853_7044697335205611008.png',
      5,
      'スラサタンナ聖処に幽棲する籠の中の鳥。夢の中でしか世界を眺めることができない。',
      Elements.Dendro,
    ),
  ),
  Candace(
    Character(
      'キャンディス',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/27/157426200/776ac3df01b790ef95a4c1b0384e828b_7302697026390199862.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/27/157426200/2f43da4ece9eabfbde6ec2fcc81b3bff_8431781766852894586.png',
      4,
      '琥珀色の左目を持つ、キングデシェレトの末裔。アアル村のガーディアンをしている。',
      Elements.Hydro,
    ),
  ),
  Cyno(
    Character(
      'セノ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/28/194600931/cb608014e47da4a071ab22cb11c76627_3623813046593848767.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/28/194600931/e09e2bda5e022611fad0dea1bb6518bb_5883842676815633002.png',
      5,
      '教令院の学者たちを監督する「大マハマトラ」。クシャレワー学院が作った『大マッハマシン』よりも効率よく仕事をこなす。',
      Elements.Electro,
    ),
  ),
  Nilou(
    Character(
      'ニィロウ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/10/09/194600931/8bd1a35ff8d58654a3f9d727d081cdb9_652461722979689351.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/10/09/194600931/586d726f9ebda3506c78beaaa41f13b6_3240276268956263027.png',
      5,
      '「ズバイルシアター」の噂に名高い踊り子。そのダンスはしなやかで美しく、彼女自身も優しく純粋な心で人と接する。',
      Elements.Hydro,
    ),
  ),
  Traveler(
    Character(
      '旅人(草)',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/23/169177528/07b09124711c2f0b81fd9d3c4171ac66_3815421716571419118.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/23/169177528/04f769b0b1671b5ffbbafefd7286b4b2_1975898965204794658.png',
      5,
      '世界の外から漂流してきた旅人。肉親が見知らぬ神に連れ去られたため、七神を探す旅に出た。',
      Elements.Dendro,
    ),
  ),
  Dori(
    Character(
      'ドリー',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/09/132746206/b4829d47e969136c6687890def3c629a_9002727722233316358.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/09/09/132746206/6539bea71efd0f839db897cfc4094362_3945412676217482723.png',
      4,
      '神出鬼没の旅商人。一番好きなものは、キラキラと輝くモラ。',
      Elements.Electro,
    ),
  ),
  Collei(
    Character(
      'コレイ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/24/103265111/4044ca9dcb140f6729753d43024c8b54_7353853820538514145.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/24/103265111/37a18b6b6865c59063003a9380f08225_2177192969678247577.png',
      4,
      'アビディアの森で活躍する見習いレンジャー。親切な言動の裏には、少し内向的な性格が隠されている。',
      Elements.Dendro,
    ),
  ),
  Tighnari(
    Character(
      'ティナリ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/23/132746206/58942db439a058f4611f27d8193f681b_4295900646890931167.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/08/23/132746206/d039c6da9285163f46b85f0241f29c17_590233914718466193.png',
      5,
      '植物学に精通している若き学者、アビディアの森のレンジャー長を務めている。まっすぐな性格で熱意があり、考えなしに行動してしまう者を指導するのが得意。',
      Elements.Dendro,
    ),
  ),
  Shikanoin_Heizou(
    Character(
      '鹿野院平蔵',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/鹿野院平藏/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Shikanoin Heizou_icon.png',
      4,
      '天領奉行の天才少年探偵。直感が鋭く、洞察力に優れている。',
      Elements.Anemo,
    ),
  ),
  Kuki_Shinobu(
    Character(
      '久岐忍',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/久岐忍/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kuki Shinobu_icon.png',
      4,
      '有能で信頼できる「荒瀧派」の二番手——注：「有能」と「信頼できる」は「荒瀧派」ではなく、二番手のことを表している。',
      Elements.Electro,
    ),
  ),
  Yelan(
    Character(
      '夜蘭',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/夜兰/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Yelan_icon.png',
      5,
      '総務司所属を称する謎の人物。しかし、総務司の名簿上では「存在しない人」となっている。',
      Elements.Hydro,
    ),
  ),
  Xiao(
    Character(
      '魈',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/魈/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Xiao_icon.png',
      5,
      '璃月を守る仙人・「夜叉」。またの名を「」、「夜叉大将」。',
      Elements.Anemo,
    ),
  ),
  Xiangling(
    Character(
      '香菱',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/香菱/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Xiangling_icon.png',
      4,
      '璃月出身で、ちょっと有名な料理人。料理に対する情熱を持っており、激辛料理が大の得意。',
      Elements.Pyro,
    ),
  ),
  Raiden_Shogun(
    Character(
      '雷電将軍',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/雷电将军/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Raiden Shogun_icon.png',
      5,
      '御建鳴神主尊大御所様。永劫不変の「永遠」を稲妻の民に約束する。',
      Elements.Electro,
    ),
  ),
  Razor(
    Character(
      'レザー',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/雷泽/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Razor_icon.png',
      4,
      '人間の町から離れた、モンド地域の奔狼領で狼と暮らす少年。勘が鋭く、動きが俊敏。',
      Elements.Electro,
    ),
  ),
  Albedo(
    Character(
      'アルベド',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/阿贝多/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Albedo_icon.png',
      5,
      '西風騎士団の首席錬金術師兼調査小隊隊長。「白亜の申し子」と呼ばれる天才。',
      Elements.Geo,
    ),
  ),
  Zhongli(
    Character(
      '鍾離',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/钟离/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Zhongli_icon.png',
      5,
      '「」に招かれた謎の。博識であり、あらゆることに精通している。',
      Elements.Geo,
    ),
  ),
  Chongyun(
    Character(
      '重雲',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/重云/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Chongyun_icon.png',
      4,
      '妖魔退治一族の少年方士。自身の「純陽の体」を抑えるために色々と苦労している。',
      Elements.Cryo,
    ),
  ),
  Diona(
    Character(
      'ディオナ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/迪奥娜/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Diona_icon.png',
      4,
      '稀な「非人類」の血統を引いている少女、「キャッツテール」の超人気バーテンダー。',
      Elements.Cryo,
    ),
  ),
  Diluc(
    Character(
      'ディルック',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/迪卢克/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Diluc_icon.png',
      5,
      'モンドの大半の酒造を掌握する貴公子。財力も人望も実力も、見くびってはならない。',
      Elements.Pyro,
    ),
  ),
  Tartaglia(
    Character(
      'タルタリヤ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/达达利亚/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Tartaglia_icon.png',
      5,
      'ファトゥス第十一位、「公子」。その戦績や名前は広く知られている。',
      Elements.Hydro,
    ),
  ),
  Xinyan(
    Character(
      '辛炎',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/辛焱/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Xinyan_icon.png',
      4,
      '璃月港唯一のロックミュージシャン。音楽と情熱で「先入観」への反抗を歌う。',
      Elements.Pyro,
    ),
  ),
  Noelle(
    Character(
      'ノエル',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/诺艾尔/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Noelle_icon.png',
      4,
      '「西風騎士団」の頼もしいメイド。いつか本当の騎士になることを夢見ている。',
      Elements.Geo,
    ),
  ),
  Xingqiu(
    Character(
      '行秋',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/行秋/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Xingqiu_icon.png',
      4,
      'よく本売り場で見かける少年。手には剣を、胸の中には義侠心を。',
      Elements.Hydro,
    ),
  ),
  Fischl(
    Character(
      'フィッシュル',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/菲谢尔/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Fischl_icon.png',
      4,
      '自称「断罪の皇女」。オズという漆黒の鴉とともに行動する謎の少女。',
      Elements.Electro,
    ),
  ),
  Mona(
    Character(
      'モナ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/莫娜/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Mona_icon.png',
      5,
      '謎の占星術師の少女。自分のことを「偉大なる占星術師モナ」と自称するが、その肩書きに相応しい実力を持っている。博学で、高慢。',
      Elements.Hydro,
    ),
  ),
  Arataki_Itto(
    Character(
      '荒瀧一斗',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/荒泷一斗/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Arataki Itto_icon.png',
      5,
      '稲妻城の花見坂で活動する「荒瀧派」の初代親分。なにっ！？荒瀧派なんて聞いたこともないだと？喧嘩売ってんのか、コラァ！？',
      Elements.Geo,
    ),
  ),
  Barbara(
    Character(
      'バーバラ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/芭芭拉/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Barbara_icon.png',
      4,
      'モンド城のみんなはバーバラが大好き。ちなみに「アイドル」という言葉は彼女が雑誌で見たものらしい。',
      Elements.Hydro,
    ),
  ),
  Hu_Tao(
    Character(
      '胡桃',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/胡桃/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Hu Tao_icon.png',
      5,
      '「」七十七代目堂主、若くして璃月のを仕切り、責任を持ってそれを執り行っている。',
      Elements.Pyro,
    ),
  ),
  Rosaria(
    Character(
      'ロサリア',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/罗莎莉亚/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Rosaria_icon.png',
      4,
      '身にまとう服装以外、何ひとつとして聖職者とは思えないシスター。冷たい言動の中には、相手を見透かす鋭さが隠されている。また、いつも一人で行動をしている。',
      Elements.Cryo,
    ),
  ),
  Kamisato_Ayaka(
    Character(
      '神里綾華',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/神里绫华/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kamisato Ayaka_icon.png',
      5,
      '稲妻「社奉行」神里家の令嬢。容姿端麗で品行方正な人物。',
      Elements.Cryo,
    ),
  ),
  Kamisato_Ayato(
    Character(
      '神里綾人',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/神里绫人/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kamisato Ayato_icon.png',
      5,
      '若く有能な社奉行神里家の現当主。穏やかで礼儀正しく、物事をそつなく処理する。',
      Elements.Hydro,
    ),
  ),
  Sucrose(
    Character(
      'スクロース',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/砂糖/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Sucrose_icon.png',
      4,
      'この世界のありとあらゆるものに強い好奇心を抱く錬金術師。研究分野は「生物錬金」。',
      Elements.Anemo,
    ),
  ),
  Shenhe(
    Character(
      '申鶴',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/申鹤/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Shenhe_icon.png',
      5,
      '仙人の弟子であり、気品溢れる女性。璃月の山奥にひっそりと住み、その気質は仙人のように孤独で淡々としている。',
      Elements.Cryo,
    ),
  ),
  Ganyu(
    Character(
      '甘雨',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/甘雨/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Ganyu_icon.png',
      5,
      '月海亭の秘書。その身には仙獣「麒麟」の血が流れている。',
      Elements.Cryo,
    ),
  ),
  Jean(
    Character(
      'ジン',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/07/31/194600931/1c7aec60047574f90ae0702ee64eaeac_1847038862351336954.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Jean_icon.png',
      5,
      '正直で真面目な蒲公英騎士。モンド西風騎士団の代理団長。',
      Elements.Anemo,
    ),
  ),
  Bennett(
    Character(
      'ベネット',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/班尼特/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Bennett_icon.png',
      4,
      'モンドの少年冒険者。その優しさにそぐわない不運の持ち主。',
      Elements.Pyro,
    ),
  ),
  Sangonomiya_Kokomi(
    Character(
      '珊瑚宮心海',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/珊瑚宫心海/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Sangonomiya Kokomi_icon.png',
      5,
      '海祇島の「現人神の巫女」、海祇島すべての事務を担当している少女。',
      Elements.None,
    ),
  ),
  Yanfei(
    Character(
      '煙緋',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/烟绯/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Yanfei_icon.png',
      4,
      '仙獣の血が流れる聡明な少女。璃月港で有名な法律家として活躍している。',
      Elements.None,
    ),
  ),
  Venti(
    Character(
      'ウェンティ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/温迪/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Venti_icon.png',
      5,
      'モンドの街にいる、数多くの自由な吟遊詩人の一人。',
      Elements.None,
    ),
  ),
  Kaedehara_Kazuha(
    Character(
      '楓原万葉',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/10/12/194600931/5b58088cd334f8f4e98495571afb03c9_3937483507477867378.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kaedehara Kazuha_icon.png',
      5,
      '稲妻より訪れし浪人。今は璃月の「南十字」武装船隊と行動を共にしている。穏やかで浮世離れした性格だが、過去に経験した様々な出来事を心の内に秘めている。',
      Elements.None,
    ),
  ),
  Sayu(
    Character(
      '早柚',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/早柚/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Sayu_icon.png',
      4,
      '「終末番」に所属する忍。小柄で、いつも眠たそうにしている。',
      Elements.None,
    ),
  ),
  Traveler_None(
    Character(
      '旅人',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/旅行者（无属性）/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Traveler_icon.png',
      5,
      '世界の外から漂流してきた旅人。肉親が見知らぬ神に連れ去られたため、七神を探す旅に出た。',
      Elements.None,
    ),
  ),
  Traveler_Anemo(
    Character(
      '旅人(風)',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/旅行者(风)/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Traveler_icon.png',
      5,
      '世界の外から漂流してきた旅人。肉親が見知らぬ神に連れ去られたため、七神を探す旅に出た。',
      Elements.Anemo,
    ),
  ),
  Traveler_Electro(
    Character(
      '旅人(雷)',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/旅行者(雷)/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Traveler_icon.png',
      5,
      '世界の外から漂流してきた旅人。肉親が見知らぬ神に連れ去られたため、七神を探す旅に出た。',
      Elements.Electro,
    ),
  ),
  Traveler_Geo(
    Character(
      '旅人(岩)',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/旅行者(岩)/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Traveler_icon.png',
      5,
      '世界の外から漂流してきた旅人。肉親が見知らぬ神に連れ去られたため、七神を探す旅に出た。',
      Elements.Geo,
    ),
  ),
  Thoma(
    Character(
      'トーマ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/托马/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Thoma_icon.png',
      4,
      '神里家の家司。稲妻で活躍する「顔役」でもある。',
      Elements.None,
    ),
  ),
  Yoimiya(
    Character(
      '宵宮',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/宵宫/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Yoimiya_icon.png',
      5,
      '「長野原花火屋」の店主。才ある花火職人で、人々の願いを花火へと託す。「夏祭りの女王」と呼ばれている。',
      Elements.None,
    ),
  ),
  Amber(
    Character(
      'アンバー',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/安柏/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Amber_icon.png',
      4,
      '元気満々な女の子、騎士団で最も優秀で、最後の偵察騎士である。',
      Elements.None,
    ),
  ),
  Aloy(
    Character(
      'アーロイ',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/埃洛伊/avatar.png',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/11/19/80830045/1fb2086af3c7933af37eda1ff9084317_3291667809200087485.png',
      5,
      'かつては異端者であったが、今は機敏で腕の立つ狩人。いついかなる時も、正確無比な矢を放つことができる。',
      Elements.None,
    ),
  ),
  Klee(
    Character(
      'クレー',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/可莉/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Klee_icon.png',
      5,
      '西風騎士団反省室の常連で、モンドの爆破スペシャリスト。人呼んで「逃げ回る太陽」。',
      Elements.None,
    ),
  ),
  Beidou(
    Character(
      '北斗',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/北斗/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Beidou_icon.png',
      4,
      '武装船隊「南十字」の頭領。豪快な姉貴。',
      Elements.None,
    ),
  ),
  Keqing(
    Character(
      '刻晴',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/刻晴/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Keqing_icon.png',
      5,
      '「璃月七星」の一人、「玉衡」。「帝君の一言で決まる璃月」に不満を持っている——だが実のところ、神は彼女のような者を高く評価している。',
      Elements.None,
    ),
  ),
  Kaeya(
    Character(
      'ガイア',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/凯亚/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kaeya_icon.png',
      4,
      '異国の顔を持つ剣士。西風騎士団の頭脳派である。',
      Elements.None,
    ),
  ),
  Ningguang(
    Character(
      '凝光',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/凝光/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Ningguang_icon.png',
      4,
      '「璃月七星」の一人、「天権」。富の多さで有名であり、全大陸で彼女に匹敵する者はまずいない。',
      Elements.None,
    ),
  ),
  Yae_Miko(
    Character(
      '八重神子',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/八重神子/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Yae Miko_icon.png',
      5,
      'の様であり、「」の編集長。華やかな見た目の裏には、思いもよらぬ知性と奸智が隠されている。',
      Elements.None,
    ),
  ),
  Eula(
    Character(
      'エウルア',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/优菈/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Eula_icon.png',
      5,
      '古き一族出身の「波花騎士」。同時に西風騎士団の遊撃小隊隊長でもある。旧貴族の末裔でありながら、敵対関係にある西風騎士団に入団した理由は、未だ謎に包まれている。',
      Elements.None,
    ),
  ),
  Gorou(
    Character(
      'ゴロー',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/五郎/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Gorou_icon.png',
      4,
      '海祇島軍隊の大将で、部下から厚く信頼されている。',
      Elements.None,
    ),
  ),
  Yun_Jin(
    Character(
      '雲菫',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/云堇/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Yun Jin_icon.png',
      4,
      '演技と創作の二つの才を持つ璃月劇の看板役者。雲菫の演じる姿は優雅でたおやかであり、まるで彼女の風格を表しているかのようである。',
      Elements.None,
    ),
  ),
  Kujou_Sara(
    Character(
      '九条裟羅',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/九条裟罗/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Kujou Sara_icon.png',
      4,
      '「天領奉行」の大将。果敢かつ勇猛である。',
      Elements.None,
    ),
  ),
  Lisa(
    Character(
      'リサ',
      'https://upload-static.hoyoverse.com/hoyolab-wiki/2022/12/15/132746206/64ff2675c8c6e9a14eafe7b6dc73aab4_5455667357274646430.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Lisa_icon.png',
      4,
      '無気力だが博学な図書館司書。スメール教令院「200年に1人」の天才卒業生。',
      Elements.None,
    ),
  ),
  Qiqi(
    Character(
      '七七',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/七七/avatar.png',
      'https://bbs.hoyolab.com/hoyowiki/picture/character/Qiqi_icon.png',
      5,
      '薬舗「不卜廬」の薬採り兼弟子、紙のように白い顔色で不死身。口数が少なく、あまり表情がない。',
      Elements.None,
    ),
  ),
  None(Character('', '', '', 0, '', Elements.None));

  final Character character;

  const Characters(this.character);

  static Characters fromName(String name) {
    for (var character in Characters.values) {
      if (character.character.charactername == name) {
        return character;
      }
    }
    return Characters.None;
  }
}
